[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Terminal settings: Echo typed input to screen + send CRLF on Enter
monitor_echo = yes
monitor_filters = send_on_enter

; Force USB CDC Serial on boot
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

; Flash settings for Waveshare ESP32-S3-Zero
board_build.mcu = esp32s3
board_build.partitions = default.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB

; Stable dependencies
lib_deps = 
    madhephaestus/ESP32Encoder@^0.10.2
    https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/3.0.8.zip
    olikraus/U8g2@^2.35.19